/* config.h generated by CMake for Basilisk II */

#ifndef MACEMU_CONFIG_H
#define MACEMU_CONFIG_H

#define PACKAGE "Basilisk II"
#define PACKAGE_NAME "Basilisk II"
#define PACKAGE_STRING "Basilisk II 1.0"
#define PACKAGE_TARNAME "BasiliskII"
#define PACKAGE_VERSION "1.0"
#define VERSION "1.0"
#define PACKAGE_BUGREPORT "Christian.Bauer@uni-mainz.de"
#define PACKAGE_URL ""

#define STDC_HEADERS 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
/* #undef HAVE_UNISTD_H */
/* #undef HAVE_STRINGS_H */
#define HAVE_FENV_H 1
/* #undef HAVE_SYS_IOCTL_H */
#define HAVE_FCNTL_H 1
/* #undef HAVE_SYS_TIME_H */
/* #undef HAVE_SYS_IOCTL_H */
/* #undef HAVE_SYS_SOCKET_H */
/* #undef HAVE_SYS_MMAN_H */
/* #undef HAVE_SYS_SELECT_H */
/* #undef HAVE_SYS_POLL_H */
/* #undef HAVE_SYS_WAIT_H */
/* #undef HAVE_SYS_FILIO_H */
/* #undef HAVE_ARPA_INET_H */
/* #undef HAVE_STROPTS_H */
/* #undef HAVE_SYS_STROPTS_H */
/* #undef HAVE_PTY_H */
/* #undef HAVE_UTIL_H */

/* #undef HAVE_PTHREADS */
/* #undef HAVE_PTHREAD_CANCEL */
/* #undef HAVE_PTHREAD_TESTCANCEL */
/* #undef HAVE_PTHREAD_COND_INIT */
/* #undef HAVE_PTHREAD_MUTEXATTR_SETPROTOCOL */
/* #undef HAVE_PTHREAD_MUTEXATTR_SETTYPE */
#define HAVE_STRDUP 1
#define HAVE_STRERROR 1
/* #undef HAVE_CFMAKERAW */
/* #undef HAVE_NANOSLEEP */
/* #undef HAVE_CLOCK_GETTIME */
/* #undef HAVE_CLOCK_NANOSLEEP */
/* #undef HAVE_GETPAGESIZE */
/* #undef HAVE_SIGACTION */

#define SIZEOF_SHORT 2
#define SIZEOF_INT 4
#define SIZEOF_LONG 4
#define SIZEOF_LONG_LONG 8
#define SIZEOF_VOID_P 8
#define SIZEOF_FLOAT 4
#define SIZEOF_DOUBLE 8
#define SIZEOF_LONG_DOUBLE 8

#define HOST_FLOAT_FORMAT IEEE_FLOAT_FORMAT

#define HAVE_WIN32_VM 1
#define HAVE_WIN32_EXCEPTIONS 1
#define HAVE_SIGSEGV_SKIP_INSTRUCTION 1
/* #undef HAVE_SIGINFO_T */
/* #undef HAVE_SIGCONTEXT_SUBTERFUGE */
/* #undef HAVE_MMAP_VM */
/* #undef HAVE_MPROTECT */

#define USE_SDL 1
#define USE_SDL_VIDEO 1
#define USE_SDL_AUDIO 1
/* #define USE_SDL2 */
/* #define USE_SDL3 */

/* #undef ENABLE_VOSF */
#define HAVE_SLIRP 1
/* #undef ENABLE_DYNGEN */
/* #undef ENABLE_MON */
#define BINCUE 1

#ifdef _MSC_VER
	#include <stddef.h>
	typedef ptrdiff_t ssize_t;
	#ifdef _M_IX86
		#ifndef __i386__
			#define __i386__
		#endif
	#elif defined(_M_AMD64)
		#ifndef __x86_64__
			#define __x86_64__
		#endif
	#endif
#endif
#ifdef _MSC_VER
	#define ATTRIBUTE_PACKED
	#define ATTRIBUTE_UNUSED
#else
	#define ATTRIBUTE_PACKED __attribute__((__packed__))
	#ifndef ATTRIBUTE_UNUSED
		#define ATTRIBUTE_UNUSED __attribute__((__unused__))
	#endif
#endif


#endif /* MACEMU_CONFIG_H */
